FROM node:8-stretch as builder

# Python
RUN apt-get update \
    && apt-get install -y python python-dev python-pip \ 
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/* 


# Install Java language server
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
RUN apt-get update && apt-get -y install openjdk-8-jdk 

RUN pip install \
    python-language-server \
    flake8 \
    autopep8 \
    futures \
    configparser

# Prepare project dirs and add a user account
RUN adduser --disabled-password --gecos '' theia && \
  adduser theia sudo && \
  echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers;

#Theia
##Needed for node-gyp, nsfw build
RUN apt-get update && apt-get install -y python build-essential

RUN chmod g+rw /home && \
  mkdir -p /home/project && \
  chown -R theia:theia /home/theia && \
  chown -R theia:theia /home/project;

USER theia
EXPOSE 3000

#prevent docker container from terminating
CMD tail -f /dev/null